<?php

class Adminconfig {
    CONST CONTROLLER_ADMINISTRATOR = 'administrator';
    CONST METHOD_ADMINISTRATOR_LOGIN = '/login/';
    CONST METHOD_ADMINISTRATOR_LOG_OUT = '/logout/';
    CONST METHOD_ADMINISTRATOR_DASHBOARD = '/dashboard/';
    CONST METHOD_ADMINISTRATOR_SITE_PARAMETER = '/siteparameter/';
    CONST METHOD_ADMINISTRATOR_TRANSACTION = '/transaction/';
    CONST METHOD_ADMINISTRATOR_PAYPAL_REQUEST = '/paypalrequest/';
    CONST METHOD_ADMINISTRATOR_CHANGE_PASSWORD = '/changepassword/';
    CONST METHOD_ADMINISTRATOR_SLIDER_SETTING = '/slidersetting/';
    
    CONST METHOD_ADMINISTRATOR_SITE_CONTENT = '/sitecontent/';
    CONST METHOD_ADMINISTRATOR_FAQ = '/faq/';
    CONST METHOD_ADMINISTRATOR_DELETE_FAQ = '/deletefaq/';
    CONST METHOD_ADMINISTRATOR_LIST = '/lists/';
    CONST METHOD_ADMINISTRATOR_VENDOR_LIST = '/vendorList/';
    CONST METHOD_ADMINISTRATOR_USER_LIST = '/userList/';
    CONST METHOD_ADMINISTRATOR_REPORT_VIOLATION_LIST = '/reportViolationList/';
    CONST METHOD_ADMINISTRATOR_DELETE_SERVICE = '/deleteservice/';
    CONST METHOD_ADMINISTRATOR_MANAGE_CATEGORY = '/addCategory/';
    CONST METHOD_ADMINISTRATOR_VIEW_CATEGORY = '/viewCategory/';
    CONST METHOD_ADMINISTRATOR_VIEW_WISH = '/viewWish/';
    CONST METHOD_ADMINISTRATOR_VIEW_SERVICE = '/viewService/';
    CONST METHOD_ADMINISTRATOR_DELETE_CATEGORY = '/deleteCategory/';
    CONST METHOD_ADMINISTRATOR_EDIT_CATEGORY = '/editCategory/';
    CONST METHOD_ADMINISTRATOR_EDIT_SERVICE = '/editService/';
    CONST METHOD_ADMINISTRATOR_DELETE_IMAGE='/deleteServiceImage/';
    CONST METHOD_ADMINISTRATOR_MANAGE_TESTIMONIALS='/manageTestimonials/';
    CONST METHOD_ADMINISTRATOR_ADD_TESTIMONIAL='/addTestimonial/';
    CONST METHOD_ADMINISTRATOR_DELETE_TESTIMONIAL='/deleteTestimonial/';
    CONST METHOD_ADMINISTRATOR_EDIT_TESTIMONIAL='/editTestimonial/';
    CONST METHOD_ADMINISTRATOR_PAGE_META_DATA='/pageMetaData/';
    CONST METHOD_ADMINISTRATOR_EDIT_PAGE_META_DATA='/editPageMetaData/';
    
    CONST METHOD_ADMINISTRATOR_WISH_DETAILS='/wishDetails/';    
    CONST METHOD_ADMINISTRATOR_WISH_APPROVED='/wishApproved/';
    CONST METHOD_ADMINISTRATOR_WISH_DELETE='/wishDeleted/';
    CONST METHOD_ADMINISTRATOR_WISH_BANNED='/wishBanned/';
    
    CONST METHOD_ADMINISTRATOR_CHANGE_PAYPAL_STATUS = '/changePaypalStatus/';

    



    CONST ADMIN_ASSET = 'assets/admin/';
    //ADMIN VIEW MODULE
    CONST VIEW_ADMIN_MASTER = 'comp/admin/adminMaster';
    CONST VIEW_ADMIN_HEADER = 'comp/admin/adminHeader';
    CONST VIEW_ADMIN_NAVIGATION = 'comp/admin/adminNavigation';
    //ADMIN VIEW COMPONENT
    CONST VIEW_ADMIN_COMP_DASBOARD = 'comp/admin/adminCompDashboard';
    CONST VIEW_ADMIN_COMP_LOGIN = 'comp/admin/adminLogin';
    CONST VIEW_ADMIN_COMP_SITE_CONTENT = 'comp/admin/adminSiteContent';
    CONST VIEW_ADMIN_COMP_FAQ = 'comp/admin/adminFaq';
    CONST VIEW_ADMIN_COMP_SITE_PARAMETER = 'comp/admin/adminSiteParameter';
    CONST VIEW_ADMIN_COMP_SITE_CHANGE_PASSWORD = 'comp/admin/adminSiteChangePassword';
    CONST VIEW_ADMIN_COMP_MANAGE_IMAGE = 'comp/admin/adminManageImg';
    CONST VIEW_ADMIN_COMP_VIEW_CATEGORY = 'comp/admin/adminViewCategory';
    CONST VIEW_ADMIN_COMP_EDIT_CATEGORY = 'comp/admin/adminEditCategory';    
    CONST VIEW_ADMIN_COMP_PAGE_META_DATA = 'comp/admin/adminPageMetaData';
    CONST VIEW_ADMIN_COMP_EDIT_META_DATA = 'comp/admin/adminEditMetaData';
    CONST VIEW_ADMIN_COMP_VIEW_WISH = 'comp/admin/adminViewWish';
    CONST VIEW_ADMIN_COMP_VIEW_WISH_DETAILS = 'comp/admin/adminWishDetails';
    CONST VIEW_ADMIN_COMP_VIEW_ALL_TRANSACTION = 'comp/admin/adminAllTransaction';
    CONST VIEW_ADMIN_COMP_VIEW_ALL_PAYPAL_REQUEST = 'comp/admin/adminAllPaypalTransaction';
}