<?php

class DBConfig {
    
    
    //define tbl_state
    CONST TABLE_STATES = 'tbl_states';
    CONST TABLE_STATES_ATT_STATE_ID = 'stateId';
    CONST TABLE_STATES_ATT_STATE_NAME = 'stateName';
    CONST TABLE_STATES_ATT_STATE_SHORT_NAME = 'stateShortName';
    CONST TABLE_STATES_ATT_COUNTRY_ID = 'countryId';

    //define tbl_city
    CONST TABLE_CITY = 'tbl_city';
    CONST TABLE_CITY_ATT_CITY_ID = 'cityId';
    CONST TABLE_CITY_ATT_CITY_NAME = 'cityName';
    CONST TABLE_CITY_ATT_STATE_ID = 'stateId';

    //define tbl_user
    CONST TABLE_USER = 'tbl_user';
    CONST TABLE_USER_ATT_USER_ID = 'userId';
    CONST TABLE_USER_ATT_USER_PASSWORD = 'userPassword';
    CONST TABLE_USER_ATT_USER_EMAIL_ADDRESS = 'userEmailAddress';
    CONST TABLE_USER_ATT_USER_LAST_LOGIN = 'lastLogin';
    CONST TABLE_USER_ATT_USER_REGISTRATION_DATE = 'registrationDate';
    CONST TABLE_USER_ATT_USER_REGISTRATION_TOKEN = 'token';
    CONST TABLE_USER_ATT_USER_STATUS = 'status';
    
    //define tbl_user_info
    CONST TABLE_USER_INFO = 'tbl_user_info';
    CONST TABLE_USER_INFO_ATT_ID = 'id';
    CONST TABLE_USER_INFO_ATT_USER_ID = 'userId';
    CONST TABLE_USER_INFO_ATT_USER_ABOUT = 'userAbout';
    CONST TABLE_USER_INFO_ATT_USER_FIRST_NAME = 'userFirstName';
    CONST TABLE_USER_INFO_ATT_USER_LAST_NAME = 'userLastName';
    CONST TABLE_USER_INFO_ATT_USER_PROFILE_PIC = 'userProfilePic';
    CONST TABLE_USER_INFO_ATT_USER_DOB = 'userDOB';
    CONST TABLE_USER_INFO_ATT_USER_ZIP_CODE = 'userZipCode';
    CONST TABLE_USER_INFO_ATT_USER_STATE_ID = 'userStateId';
    CONST TABLE_USER_INFO_ATT_USER_CITY_ID = 'userCityId';
    CONST TABLE_USER_INFO_ATT_USER_ADDRESS = 'userAddress';
    CONST TABLE_USER_INFO_ATT_USER_PHONE = 'userPhone';
    
    CONST TABLE_ADMIN = 'tbl_admin';
    CONST TABLE_ADMIN_ATT_ADMIN_ID = 'adminId';
    CONST TABLE_ADMIN_ATT_ADMIN_USERNAME = 'adminUsername';
    CONST TABLE_ADMIN_ATT_ADMIN_PASSWORD = 'adminPassword';
    CONST TABLE_ADMIN_ATT_ADMIN_LAST_LOGIN_TIME = 'adminLastLoginTime';
    CONST TABLE_ADMIN_ATT_ADMIN_IS_ACTIVE = 'adminIsActive';
    CONST TABLE_ADMIN_ATT_ADMIN_PREVILEDGE = 'adminPreviledge';
    
    CONST TABLE_CONTENT = 'tbl_content';
    CONST TABLE_CONTENT_ATT_CONTENT_ID = 'contentId';
    CONST TABLE_CONTENT_ATT_CONTENT_NAME = 'contentName';
    CONST TABLE_CONTENT_ATT_CONTENT_TITLE = 'contentTitle';
    CONST TABLE_CONTENT_ATT_CONTENT_DETAILS = 'contentDetails';
    
    CONST TABLE_FAQ = 'tbl_faq';
    CONST TABLE_FAQ_ATT_FAQ_ID = 'faqId';
    CONST TABLE_FAQ_ATT_FAQ_QUESTION = 'faqQuestion';
    CONST TABLE_FAQ_ATT_FAQ_ANSWER = 'faqAnswer';
    CONST TABLE_FAQ_ATT_ADDED_TIME = 'addedTime';
    
    
    
    CONST TABLE_SETTINGS = 'tbl_settings';
    CONST TABLE_SETTINGS_ATT_ID = 'id';
    CONST TABLE_SETTINGS_ATT_SITE_TITLE = 'siteTitle';
    CONST TABLE_SETTINGS_ATT_SITE_META_KEYWORD = 'siteMetaKeyword';
    CONST TABLE_SETTINGS_ATT_SITE_META_DESCRIPTION = 'siteMetaDescription';
    CONST TABLE_SETTINGS_ATT_SITE_LOGO = 'siteLogo';
    CONST TABLE_SETTINGS_ATT_SITE_EMAIL = 'siteEmail';
    CONST TABLE_SETTINGS_ATT_SITE_PHONE = 'sitePhone';
    CONST TABLE_SETTINGS_ATT_SITE_VENDOR_LOGO = 'siteVendorLogo';
    CONST TABLE_SETTINGS_ATT_HIDE_HOME_CONTENT = 'hideHomeContent';
    
    CONST TABLE_CURRENCY = 'tbl_currency';
    CONST TABLE_CURRENCY_ATT_ID = 'id';
    CONST TABLE_CURRENCY_ATT_CURRENCY_NAME = 'currencyName';
    CONST TABLE_CURRENCY_ATT_CURRENCY_SYMBOL = 'currencySymbol';
    
    CONST TABLE_WISH = 'tbl_wish';
    CONST TABLE_WISH_ATT_WISH_ID = 'wishId';
    CONST TABLE_WISH_ATT_WISH_TITLE = 'wishTitle';
    CONST TABLE_WISH_ATT_WISH_DESCRIPTION = 'wishDescription';
    CONST TABLE_WISH_ATT_WISH_PHOTO = 'wishPhoto';
    CONST TABLE_WISH_ATT_WISH_GOAL_AMOUNT = 'wishGoalAmount';
    CONST TABLE_WISH_ATT_WISH_CURRENCY_ID = 'wishCurrencyId';
    CONST TABLE_WISH_ATT_WISH_CATEGORY_ID = 'wishCategoryId';
    CONST TABLE_WISH_ATT_WISH_USER_ID = 'wishUserId';
    CONST TABLE_WISH_ATT_WISH_ADDED_DATE = 'wishAddedDate';
    CONST TABLE_WISH_ATT_WISH_STATE_ID = 'wishStateId';
    CONST TABLE_WISH_ATT_WISH_CITY_ID = 'wishCityId';
    CONST TABLE_WISH_ATT_WISH_GRANT_DATE = 'wishGrantDate';
    CONST TABLE_WISH_ATT_WISH_STATUS = 'wishStatus';
    
    CONST TABLE_WISH_CATEGORY = 'tbl_wish_category';
    CONST TABLE_WISH_CATEGORY_ATT_CATEGORY_ID = 'categoryId';
    CONST TABLE_WISH_CATEGORY_ATT_CATEGORY_NAME = 'categoryName';
    
    CONST TABLE_WISH_COMMENTS = 'tbl_wish_comments';
    CONST TABLE_WISH_COMMENTS_ATT_COMMENTS_ID = 'commentsId';
    CONST TABLE_WISH_COMMENTS_ATT_USER_ID = 'userId';
    CONST TABLE_WISH_COMMENTS_ATT_WISH_ID = 'wishId';
    CONST TABLE_WISH_COMMENTS_ATT_COMMENTS = 'comments';
    CONST TABLE_WISH_COMMENTS_ATT_TIME = 'time';
    
    //define tbl_page_seo
    CONST TABLE_PAGE_SEO = 'tbl_page_seo';
    CONST TABLE_PAGE_SEO_ATT_ID = 'id';
    CONST TABLE_PAGE_SEO_ATT_PAGE_TITLE = 'pageTitle';
    CONST TABLE_PAGE_SEO_ATT_PAGE_ID = 'pageId';
    CONST TABLE_PAGE_SEO_ATT_PAGE_META_DESCRIPTION = 'pageMetaDescription';
    CONST TABLE_PAGE_SEO_ATT_PAGE_META_KEYWORD = 'pageMetaKeyword';
    CONST TABLE_PAGE_SEO_ATT_PAGE_AUTHOR = 'pageAuthor';
    
    //define tbl_wish_donate
    CONST TABLE_WISH_DONATE = 'tbl_wish_donate';
    CONST TABLE_WISH_DONATE_ATT_DONATE_ID = 'donateId';
    CONST TABLE_WISH_DONATE_ATT_WISH_ID = 'wishId';
    CONST TABLE_WISH_DONATE_ATT_AMOUNT = 'amount';
    CONST TABLE_WISH_DONATE_ATT_USER_ID = 'userId';
    CONST TABLE_WISH_DONATE_ATT_TOKEN = 'token';
    CONST TABLE_WISH_DONATE_ATT_PAYER_ID = 'payerID';
    CONST TABLE_WISH_DONATE_ATT_GETEWAY_REFERENCE = 'gatewayReference';
    CONST TABLE_WISH_DONATE_ATT_PAY_TIME = 'payTime';
    CONST TABLE_WISH_DONATE_ATT_COMMENTS = 'comments';
    
    CONST TABLE_USER_PAYPAL = 'tbl_user_paypal';
    CONST TABLE_USER_PAYPAL_ATT_ID = 'id';
    CONST TABLE_USER_PAYPAL_ATT_USER_ID = 'userId';
    CONST TABLE_USER_PAYPAL_ATT_USERNAME = 'username';
    CONST TABLE_USER_PAYPAL_ATT_PASSWORD = 'password';
    CONST TABLE_USER_PAYPAL_ATT_SIGNATURE = 'signature';
    CONST TABLE_USER_PAYPAL_ATT_STATUS = 'status';
    
    CONST TABLE_USER_MESSAGES = 'tbl_user_messages';
    CONST TABLE_USER_MESSAGES_ATT_ID = 'id';
    CONST TABLE_USER_MESSAGES_ATT_FROM = 'from';
    CONST TABLE_USER_MESSAGES_ATT_TO = 'to';
    CONST TABLE_USER_MESSAGES_ATT_MESSAGE = 'message';
    CONST TABLE_USER_MESSAGES_ATT_SENT_TIME = 'sentTime';
    CONST TABLE_USER_MESSAGES_ATT_IS_READ = 'isRead';
}
